# Generated by Django 4.2 on 2023-05-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_alter_tasklist_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasklist',
            unique_together=set(),
        ),
    ]
